// Winning conditions of each row, shown as a tooltip on the yaku name.
// Han are closed-hand values (Phase 1 is closed tsumo, East round and seat).
export const YAKU_CONDITIONS: Record<string, string> = {
  normal: '役の条件を付けない4面子1雀頭の向聴数（基準値）。七対子・国士無双は別の行。',
  tanyao: '1翻。2〜8の数牌だけで作る。么九牌（1・9・字牌）を含まない。',
  pinfu: '1翻・門前。4面子すべて順子、雀頭が役牌でない、待ちが両面。',
  iipeikou: '1翻・門前。同じ順子を2組（例 223344萬）。',
  ryanpeikou: '3翻・門前。一盃口を2組。一盃口とは複合しない。',
  sanshoku: '2翻。萬子・筒子・索子で同じ数の順子（例 123萬 123筒 123索）。',
  sanshoku_doukou: '2翻。萬子・筒子・索子で同じ数の刻子。',
  ittsu: '2翻。同じ色で123・456・789の順子。',
  chanta: '2翻。すべての面子と雀頭に么九牌（1・9・字牌）を含み、順子を1つ以上含む。',
  junchan: '3翻。すべての面子と雀頭に1か9を含み、字牌を使わない。順子を1つ以上含む。',
  honroutou: '2翻。1・9・字牌だけで作る（刻子4つ＋雀頭、または七対子の形）。',
  honitsu: '3翻。1種類の数牌と字牌だけで作る。',
  chinitsu: '6翻。1種類の数牌だけで作る。',
  toitoi: '2翻。4面子すべて刻子。',
  sanankou: '2翻。暗刻（鳴かずにそろえた刻子）を3つ。',
  shousangen: '2翻。白・發・中のうち2つを刻子、残り1つを雀頭。役牌2つも別に付く。',
  haku: '1翻。白の刻子。',
  hatsu: '1翻。發の刻子。',
  chun: '1翻。中の刻子。',
  ton: '2翻。東の刻子。東場・東家なので場風と自風で2翻。',
  chiitoitsu: '2翻・門前。異なる対子を7組。同じ牌4枚は2組と数えない。',
  kokushi: '役満・門前。1・9・字牌の13種を1枚ずつ＋そのうち1種をもう1枚。',
  suuankou: '役満・門前。暗刻を4つ。',
  daisangen: '役満。白・發・中をすべて刻子。',
  tsuuiisou: '役満。字牌だけで作る（七対子の形も可）。',
  shousuushii: '役満。東南西北のうち3つを刻子、残り1つを雀頭。',
  daisuushii: '役満。東南西北をすべて刻子。',
  ryuuiisou: '役満。2・3・4・6・8索と發だけで作る。',
  chinroutou: '役満。1と9の数牌だけで作る。',
  chuuren: '役満・門前。同じ色の1112345678999＋同じ色の1枚。',
};
